aes_encryption_key: "{{ vault_aes_encryption_key }}"

local_username_15: "adminuser"
local_secret_15: "{{ vault_local_secret_15 }}"

local_username_7: "nonadminuser"
local_secret_7: "{{ vault_local_secret_7 }}"

enable_secret: "{{ vault_enable_secret }}"
