# group_vars/access_switches/radius.yaml
radius_servers:
  - ip: 10.11.1.1
    auth_port: 1812
    acct_port: 1813
    timeout: 4
    retransmit: 3
  - ip: 10.11.1.2
    auth_port: 1812
    acct_port: 1813
    timeout: 4
    retransmit: 3

radius_tester_username: "RADIUSTESTING"
radius_shared_key: "{{ vault_radius_key }}"
radius_deadtime: 15
